version: 2
jobs:
  build:
    branches:
      only:
        - build-pipeline
    docker:
      # This docker image is created from the Dockerfile in
      # this repository.
      - image: ministryofjustice/cloud-platform-user-guide
        environment:
          DOMAIN: user-guide-compiled.cloud-platform.service.justice.gov.uk

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle exec middleman build --build-dir docs
      - run: touch docs/.nojekyll
      - run: echo ${DOMAIN} > docs/CNAME
