version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # This docker image is created from the Dockerfile in
      # this repository.
      - image: ministryofjustice/cloud-platform-user-guide
        environment:
          # This is the domain on which the user guide is served
          DOMAIN: user-guide.cloud-platform.service.justice.gov.uk

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            # this SSH key must be configured in the account of the github user
            # who will be pushing changes. The corresponding private key must
            # be added to the project on circleci.com
            # Currently, this is the 'cloud-platform-moj' github user account.
            # The GitHub user must be added to the cloud-platform-user-guide
            # repository as an admin.
            - "b4:43:a7:ce:06:8d:ef:4e:11:71:de:75:65:6c:fa:a2"

      - checkout

        # Don't build and push if the latest commit only includes changes to the compiled static files.
        # This prevents circleci from going into an endless loop, where it pushes changes to docs/ and
        # then starts a new build because it sees changes to the repo. This script tests for that, and
        # exits with an error if the build should not proceed.
      - run: bin/pipeline-should-build.sh
      - run: bundle exec middleman build --build-dir docs
      - run: touch docs/.nojekyll
      - run: echo ${DOMAIN} > docs/CNAME
