name: Auto-approve a pull request

on:
  workflow_dispatch:
    branches:
      - 'main'
  # pull_request

jobs:
  check-diff:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Run git diff against repository
        run: |
          git diff origin/main HEAD > changes

      - run: |
          cat changes

      - name: Copy changes file so next check can read it
        run: |
          mkdir ${HOME}/work/_temp/_github_home
          cp ${HOME}/changes ${HOME}/work/_temp/_github_home/.

      - name: Auto-approval check
        uses: ministryofjustice/github-actions/approve-doc-review@add-docs-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
