name: Publish

on:
  push:
    branches:
      - "tech-docs-2"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: digitalronin/ug
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bundle exec middleman build --build-dir docs
    - name: Run the script
      run: bin/publish.sh
      env:
        PUBLISHING_GIT_TOKEN: ${{ secrets.PUBLISHING_GIT_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: cloud-platform-moj
        GITHUB_PAGES_REPO_AUTHOR_EMAIL: platforms@digital.justice.gov.uk
        GITHUB_PAGES_REPO_NAME: cloud-platform-user-guide-publish
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: docs
